# .goreleaser.yml
project_name: dnsmorph
# Build customization
builds:
  - binary: dnsmorph
    goos:
      - windows
      - linux
    goarch:
      - amd64
      - 386
      - arm
      - arm64
# Archive customization
archive:
  format: tar.gz
  replacements:
    amd64: 64-bit
    386: 32-bit
  format_overrides:
    - goos: windows
      format: zip
  files:
    - data/GeoLite2-City.zip